### ISSUE TITLE
Segmentation fault when the application exits while a connection is open

### ISSUE THREAD

**Issue by carbn** [nikhilm/qhttpserver#32]
When the application quits while a client has an open connection the program segfauls. This is not an issue if the requests are handled immediately, but when the processing takes longer a ctrl-c handler for example can crash the program easily.

I have modified the helloworld example in my own repo (segfault branch) to reproduce this crash:

https://github.com/carbn/qhttpserver/tree/segfault

**Comment by Mankalas** [comment]
Hello!

I had this segfault when testing a simple server/client communication with QTest.
Azadkuh's code fixes the issue and seems like a good solution. Can you please integrate his fix into your master branch?
