### ISSUE TITLE
body() appears to be empty

### ISSUE THREAD

**Issue by cshiel** [nikhilm/qhttpserver#51]
Body is always empty it seems.

**Comment by cshiel** [comment]
In QHttpRequest I POST some data in the body and its not coming in at all.

**Comment by axed** [comment]
https://github.com/nikhilm/qhttpserver/issues/20

**Comment by cshiel** [comment]
Not quite. I can get the data if I want but why is data() always empty? I can't find a way to set it either.

**Comment by axed** [comment]
So when are you accessing the data with data()? When the HTTP-Headers arrived or when the actual body arrived?

**Comment by cshiel** [comment]
As per the streaming body data example I am looking in the accumulate() method.
