### ISSUE TITLE
Writing headers without a status code

### ISSUE THREAD

**Issue by mseker-issd** [nikhilm/qhttpserver#53]
```cpp
void QHttpResponse::writeHeaders()
```
method is private and called automatically  by
```cpp
QHttpResponse::writeHead(int status)
```
right after writing the status code to the client.

This makes it impossible to write headers without writing a status code which prevents me from creating an mjpeg server that needs to respond to clients in the following format : 
```html
HTTP/1.0 200 OK
Content-Type: multipart/x-mixed-replace;boundary=boundary
--boundary

--boundary
Content-Type: image/jpeg
Content-Length: 67856

<binary JPEG image data>
--boundary
Content-Type: image/jpeg
Content-Length: 52856

<binary JPEG Image data>
--boundary 
...
```

Suggestion : Cancel the automatic call to ```QHttpResponse::writeHeaders()``` and make it public.

**Comment by axed** [comment]
I am afraid your post doesn't make any sense.

You cannot just state 
> This makes it impossible to write headers without writing a status code which prevents me from creating an mjpeg server that needs to respond to clients in the following format :

And write 

> HTTP/1.0 200 OK

just one line later.

Please read https://tools.ietf.org/html/rfc1945 before you take any further actions.

**Comment by mseker-issd** [comment]
How am i supposed to write 

Content-Type: image/jpeg
Content-Length: 52856

headers before every image without writing status code ?

**Comment by axed** [comment]
> How am i supposed to...

You're not:

> https://tools.ietf.org/html/rfc1945#section-6

**Comment by mseker-issd** [comment]
Multipart responses may contain additional headers :

https://tools.ietf.org/html/rfc1945#section-3.6.2

**Comment by axed** [comment]
I see your point, but those ain't typical HTTP headers - just parts of them wraped in the *HTTP response __body__*.
