### ISSUE TITLE
Host static web pages

### ISSUE THREAD

**Issue by jiakuan** [nikhilm/qhttpserver#54]
Hi there, QHttpServer looks promising for our projects.

We would like to use QHttpServer to host a static web site within a QT application. Is there a simple way to host the HTML/CSS/JS files etc from QT resources?

Thanks in advance!
Jake

**Comment by axed** [comment]
Yes.

**Comment by jiakuan** [comment]
Shall I write a custom handler for that, or is there a simple function
(e.g. loadStaticSite) can do it?
Thank you.

**Comment by axed** [comment]
There is a handler for incoming requests. It's up to you to handle that request in whatever way you think is suiting your purpose.

**Comment by jiakuan** [comment]
Got it. Thanks
