### ISSUE TITLE
How to handle a request from client?

### ISSUE THREAD

**Issue by sk2212** [nikhilm/qhttpserver#56]
Hello,

I have some problems to understand how to handle a request which is send by a client. I understand (because of the examples) how to send a response to a client but not the way in the other direction.

Can you help me?

Furthermore, the next step would be to use the request within QML in "newConnection()" signal.

For the qml example have a look here:

https://github.com/rschroll/qhttpserver/blob/master/examples/qml/app.qml

I think you already use the because of the forking...

**Comment by axed** [comment]
> the way in the other direction.

http://doc.qt.io/qt-5/qtqml-xmlhttprequest-example.html

> Furthermore, the next step would be to use the request within QML in "newConnection()" signal.

I would recommend to you, not to handle such things in QML, but instead do that as a QML-C++ binding, so you can access C++ methods from QML ... but thats a matter of taste i guess.
